title: Kyla's help reference
description: [describe the thing and the other thing]
theme: just-the-docs
color_scheme: dark
url: https://kylahelpref.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
